<?php
    /*
    Win10
    */
    echo"当前文件路径:".__FILE__;
    echo"<br>当前行数:".__LINE__;
    echo"<br>PHP版本:".PHP_VERSION;
    echo"<br>当前系统:".PHP_OS;
    echo"<br>圆周率:".pi();
    echo"<br>PHP".pi();
?>
